// extensions

export const TOGGLE_EXTENSION = "TOGGLE_EXTENSION";
export const LOADED_EXTENSION = "LOADED_EXTENSION";
export const LOADING_EXTENSION = "LOADING_EXTENSION";

// advanced controls

export const UPDATE_ADVANCED_SETTINGS = "UPDATE_ADVANCED_SETTINGS";
export const SAVE_ADVANCED_SETTINGS = "SAVE_ADVANCED_SETTINGS";
export const SAVING_ADVANCED_SETTINGS = "SAVING_ADVANCED_SETTINGS";
export const SAVED_ADVANCED_SETTINGS = "SAVED_ADVANCED_SETTINGS";
